#!/bin/sh

# container-tools - Manage systemd-nspawn containers
# Copyright (C) 2014-2016 Daniel Baumann <daniel.baumann@open-infrastructure.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

COMMAND="$(basename ${0})"

MACHINES="/var/lib/machines"

Usage ()
{
	echo "Usage: container ${COMMAND}" >&2
	exit 1
}

if [ -n "${1}" ]
then
	Usage
fi

# Run
CONTAINERS="$(cd "${MACHINES}" && find -maxdepth 1 -type d -and -not -name 'lost+found' -printf '%P\n' | sort)"

echo RUNNING

for CONTAINER in ${CONTAINERS}
do
	STATE="$(machinectl show ${CONTAINER} 2>&1 | awk -F= '/^State=/ { print $2 }')"

	case "${STATE}" in
		running)
			echo " ${CONTAINER}"
			;;
	esac
done

echo
echo STOPPED

for CONTAINER in ${CONTAINERS}
do
	STATE="$(machinectl show ${CONTAINER} 2>&1 | awk -F= '/^State=/ { print $2 }')"

	case "${STATE}" in
		running)
			;;

		*)
			echo " ${CONTAINER}"
			;;
	esac
done
